/**
 * Copyright © 2025 BANKX. All rights reserved. The software and hardware products described in this
 * documentation/material are the intellectual property of BANKX. Any reproduction or unauthorized
 * use, without the prior express written consent of BANKX, is strictly prohibited.
 */
package com.ms.bankx.application.mapper;

import com.ms.bankx.domain.model.Employee;
import com.ms.bankx.infrastructure.adapter.jpa.entity.EmployeeEntity;
import java.util.List;
import org.mapstruct.Mapper;

/**
 * Interface that defines the methods to mapping between Employee (Domain) and EmployeeEntity (JPA)
 * the implementation is automatic generated by spring in compilation time.
 */
@Mapper(componentModel = "spring")
public interface EmployeePersistenceMapper {
    
  /**
   * Method that mapper object Employee to EmployeeEntity.
   * @param employee data to persist.
   * @return EmployeeEntity from employee.
   */
  EmployeeEntity toEntity(Employee employee);
    
  /**
   * Method that mapper object EmployeeEntity to Employee.
   * @param employeeEntity data to domain.
   * @return Employee from EmployeeEntity.
   */
  Employee toDomain(EmployeeEntity employeeEntity);
    
  /**
   * Method that mapper object list of EmployeeEntity to Employee list.
   * @param entityList EmployeeEntity list
   * @return Employee list from EmployeeEntity list.
   */
  List<Employee> toDomainList(List<EmployeeEntity> entityList);
}
