/**
 * Copyright © 2025 BANKX. All rights reserved. The software and hardware products described in this
 * documentation/material are the intellectual property of BANKX. Any reproduction or unauthorized
 * use, without the prior express written consent of BANKX, is strictly prohibited.
 */
package com.ms.bankx.application.mapper;

import com.ms.bankx.domain.model.Employee;
import com.ms.bankx.infrastructure.adapter.rest.dto.EmployeeRequest;
import com.ms.bankx.infrastructure.adapter.rest.dto.EmployeeResponse;
import java.util.List;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * Interface that defines the methods to mapping between Employee (Domain) and Employee request
 * the implementation is automatic generated by spring in compilation time.
 */
@Mapper(componentModel = "spring")
public interface EmployeeApiMapper {
    
    /**
     * Method that mapper object request to employee of domain.
     * @param request the data received into of request.
     * @return object domain from request.
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "systemRegistrationDate", ignore = true)
    Employee toDomain(EmployeeRequest request);
    
    /**
     * Method that mapper object request list to employee list of domain.
     * @param requestList the data List received into of request.
     * @return object List domain from argument.
     */
    List<Employee> toDomainList(List<EmployeeRequest> requestList);
    
    /**
     * Method that mapper object employee of domain to response.
     * @param employee the data received into of argument.
     * @return object EmployeResponse from employee.
     */
    EmployeeResponse toResponse(Employee employee);
    
    /**
     * Method that mapper object employee list of domain to response list.
     * @param employeeList the data received into of argument.
     * @return object EmployeResponse list from employee list.
     */
    List<EmployeeResponse> toResponseList(List<Employee> employeeList);
}
